# Dockerfile.bot
FROM python:3.12-slim

# Установка рабочей директории внутри контейнера
WORKDIR /bot

# Копируем файл с зависимостями для бота
COPY telegram_bot/requirements.txt /bot/

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код бота
COPY telegram_bot/ /bot/

# Команда для запуска бота
CMD ["python", "main.py"]
