version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: flower_backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: flower_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=http://backend:8000/api/
    depends_on:
      - backend

  admin_bot:
    build:
      context: .
      dockerfile: Dockerfile.admin_bot
    container_name: flower_admin_bot
    environment:
      - ADMIN_BOT_TOKEN=${ADMIN_BOT_TOKEN}
      - API_URL=http://backend:8000/api/
    depends_on:
      - backend
